### ISSUE TITLE
Development Environment

### ISSUE THREAD

**Issue by semohr** [SciCatProject/frontend#1798]
Hello y'all,

what is the minimal approach to get a developer environment going? I'm mainly interested in the frontend for now.

The documentation points to the scicatlive or [is broken](https://www.scicatproject.org/documentation/Development/v4.x/Running.html). As far as I can see scicatlive does not include a straight forward way to get an **editable** frontend repo in dev mode. Am I missing something?

I would expect to be able to build the container myself and live mount the frontend repository. For most containerized FOSS projects this is the quasi standard. 

Your compose setup seem quite complicated and I have not yet had an indepth look. In general I would expect something like this:
```yaml

services:
    frontend:
        container_name: scicat_frontend
        build:
            context: ../
            dockerfile: docker/Dockerfile.frontend
        volumes:
            # Live mount for debuging
            - ./:/app
    [other services from registry]
```

I hope I'm not missing something here. Adding something like a standard dev setup would improve on-boarding significantly imo...

Best, Sebastian
