### ISSUE TITLE
undefined scientific metadata instead of 0.0 float

### ISSUE THREAD

**Issue by jkotan** [SciCatProject/frontend#989]
### Summary

When I ingest  zero float scientificMetadata for raw dataset with REST API e.g.
```json
            "scientificMetadata": {
                       ...
                "m1tra": {
                        "depends_on": "",
                        "source": "haspp08lisa2:10000/p08/motor/lisa2.27/Position",
                        "source_name": "m1tra",
                        "source_type": "TANGO",
                        "strategy": "INIT",
                        "transformation_type": "translation",
                        "type": "NX_FLOAT",
                        "unit": "mm",
                        "value": 0.0,
                        "vector": [
                            0.0,
                            1.0,
                            0.0
                        ]
                    },
              ...
        }
```
in  the JSON metadata view I get
```
m1tra:
    depends_on: ""
    source: "haspp08lisa2:10000/p08/motor/lisa2.27/Position"
    source_name: "m1tra"
    source_type: "TANGO"
    strategy: "INIT"
    transformation_type: "translation"
    type: "NX_FLOAT"
    unit: "mm"
    value: 0
    vector: Array[3] [0,1,0]
    unitSI: "mm"
````
so the zero float value is converted to the zero integer and there is no `valueSI`.
Moreover if I see it in the main scientificMetadata view I get
``` 
   m1tra:  undefined
```
Is it by purpose  or a bug?

### Steps to Reproduce

Ingest the above scientific metadata

### Current Behaviour
``` 
   m1tra:  undefined
```

### Expected Behaviour
``` 
    m1tra:  0 (mm)
```
or 
``` 
    m1tra:  0.0 (mm)
```
